'<ADbasic Header, Headerversion 001.001>
'<Header End>
' ----- Configuration -----

set_com_rate = 1

set_sampling_rate = 400e3
set_com_rate = 1
set_window_time = 1
  
' Define level limits
set_state0_high_volt = 0
set_state0_low_volt  = 0
set_state1_high_volt = 0
set_state1_low_volt  = 0

' Range limits (there are addition hardware limits)
set_range_low_volt  = -9
set_range_high_volt =  0

' Feedback values
set_feedback_status = 0
set_feedback_factor = 0
set_feedback_rate   = 0
